// phase-data.js — per-project PHASE breakdown: planned baseline vs actual.
// Generated by fetch-phases.js. Planned <- baseline sheet, Actual <- Project Plan.
window.PHASE_DATA = {
  "generatedAt": "2026-08-14",
  "projects": []
};
