// phase-data.js — per-project PHASE breakdown: planned baseline vs actual.
// Planned dates come from each project's frozen "Planned ... Do Not Touch" baseline sheet.
// Actual dates come from the live Project Plan's parent-phase rows.
// Only projects that HAVE a baseline sheet appear here; others show "no baseline yet".
//
// Shape: projects[] = {
//   code, name, pod, lob,
//   phases[] = { phase, plannedStart, plannedEnd, actualStart, actualEnd, status }
// }
// Regenerated by the fetch pipeline as more baselines are created.
window.PHASE_DATA = {
  "generatedAt": "2026-07-31",
  "projects": [
    {
      "code": "JJ-1202",
      "name": "Scottsdale Phase 3 and 4 - Reinstatements, Renewals and Expansion",
      "pod": "PL Pod",
      "lob": "Personal Lines",
      "phases": [
        { "phase": "Planning & Discovery",              "plannedStart": "2026-07-27", "plannedEnd": "2026-07-27", "actualStart": "2026-07-27", "actualEnd": "2026-07-27", "status": "Complete" },
        { "phase": "Requirements & Design",             "plannedStart": "2026-07-27", "plannedEnd": "2026-07-31", "actualStart": "2026-07-27", "actualEnd": "2026-07-31", "status": "In Progress" },
        { "phase": "Development",                        "plannedStart": "2026-07-27", "plannedEnd": "2026-08-18", "actualStart": "2026-07-27", "actualEnd": "2026-08-18", "status": "Not Started" },
        { "phase": "Alpha Testing (Dev Testing)",        "plannedStart": "2026-08-19", "plannedEnd": "2026-08-27", "actualStart": "2026-08-19", "actualEnd": "2026-08-27", "status": "Not Started" },
        { "phase": "Acceptance Testing (UAT/Pre-Prod)",  "plannedStart": "2026-08-28", "plannedEnd": "2026-09-14", "actualStart": "2026-08-28", "actualEnd": "2026-09-14", "status": "Not Started" },
        { "phase": "Release",                            "plannedStart": "2026-09-15", "plannedEnd": "2026-09-15", "actualStart": "2026-09-15", "actualEnd": "2026-09-15", "status": "Not Started" },
        { "phase": "Stabilization (Hypercare)",          "plannedStart": "2026-09-16", "plannedEnd": "2026-09-16", "actualStart": "2026-09-16", "actualEnd": "2026-09-16", "status": "Not Started" },
        { "phase": "Retrospective and Closeout",         "plannedStart": "2026-09-17", "plannedEnd": "2026-09-18", "actualStart": "2026-09-17", "actualEnd": "2026-09-18", "status": "Not Started" }
      ]
    }
  ]
};
