// phase-data.js — per-project PHASE breakdown: planned baseline vs actual.
// Generated by fetch-phases.js. Planned <- baseline sheet, Actual <- Project Plan.
window.PHASE_DATA = {
  "generatedAt": "2026-09-02",
  "projects": [
    {
      "code": "JJ-1065",
      "name": "P3: Quote and Printing Improvement",
      "pod": "Program Pod",
      "lob": "Program",
      "phases": [
        {
          "phase": "Requirements & Design",
          "plannedStart": "2026-03-12",
          "plannedEnd": "2026-04-13",
          "actualStart": "2026-03-12",
          "actualEnd": "2026-04-13"
        },
        {
          "phase": "Development",
          "plannedStart": "2026-04-13",
          "plannedEnd": "2026-12-30",
          "actualStart": "2026-04-13",
          "actualEnd": "2026-12-30"
        },
        {
          "phase": "Alpha Testing (Dev Testing)",
          "plannedStart": "2026-04-28",
          "plannedEnd": "2027-01-20",
          "actualStart": "2026-04-28",
          "actualEnd": "2027-01-20"
        },
        {
          "phase": "Acceptance Testing (UAT/Pre-Prod)",
          "plannedStart": "2027-01-20",
          "plannedEnd": "2027-02-16",
          "actualStart": "2027-01-20",
          "actualEnd": "2027-02-16"
        },
        {
          "phase": "Release",
          "plannedStart": "2027-02-17",
          "plannedEnd": "2027-02-23",
          "actualStart": "2027-02-17",
          "actualEnd": "2027-02-23"
        },
        {
          "phase": "Stabilization (Hypercare)",
          "plannedStart": "2027-02-23",
          "plannedEnd": "2027-03-09",
          "actualStart": "2027-02-23",
          "actualEnd": "2027-03-09"
        },
        {
          "phase": "Retrospective and Closeout",
          "plannedStart": "2027-03-10",
          "plannedEnd": "2027-03-10",
          "actualStart": "2027-03-10",
          "actualEnd": "2027-03-10"
        }
      ]
    },
    {
      "code": "JJ-1202",
      "name": "Scottsdale Phase 3 and 4 - Reinstatements, Renewals and Expansion",
      "pod": "PL Pod",
      "lob": "Personal Lines",
      "phases": [
        {
          "phase": "Planning & Discovery",
          "plannedStart": "2026-07-27",
          "plannedEnd": "2026-07-27",
          "actualStart": "2026-07-27",
          "actualEnd": "2026-07-27"
        },
        {
          "phase": "Requirements & Design",
          "plannedStart": "2026-07-27",
          "plannedEnd": "2026-07-31",
          "actualStart": "2026-07-27",
          "actualEnd": "2026-07-31"
        },
        {
          "phase": "Development",
          "plannedStart": "2026-07-27",
          "plannedEnd": "2026-08-18",
          "actualStart": "2026-07-27",
          "actualEnd": "2026-08-25"
        },
        {
          "phase": "Alpha Testing (Dev Testing)",
          "plannedStart": "2026-08-19",
          "plannedEnd": "2026-08-27",
          "actualStart": "2026-08-26",
          "actualEnd": "2026-09-03"
        },
        {
          "phase": "Acceptance Testing (UAT/Pre-Prod)",
          "plannedStart": "2026-08-28",
          "plannedEnd": "2026-09-14",
          "actualStart": "2026-09-04",
          "actualEnd": "2026-09-21"
        },
        {
          "phase": "Release",
          "plannedStart": "2026-09-15",
          "plannedEnd": "2026-09-15",
          "actualStart": "2026-09-22",
          "actualEnd": "2026-09-22"
        },
        {
          "phase": "Stabilization (Hypercare)",
          "plannedStart": "2026-09-16",
          "plannedEnd": "2026-09-29",
          "actualStart": "2026-09-23",
          "actualEnd": "2026-10-14"
        },
        {
          "phase": "Retrospective and Closeout",
          "plannedStart": "2026-09-30",
          "plannedEnd": "2026-10-07",
          "actualStart": "2026-10-15",
          "actualEnd": "2026-10-22"
        }
      ]
    }
  ]
};
