// RM probe output — read-only sample for inspection. Safe to delete.
window.RM_PROBE = {
  "generatedAt": "2026-07-22T20:16:38.869Z",
  "report": [
    "=== RM PROBE (read-only) ===\n",
    "AUTH OK. Sample users (5):",
    "  - Bertram Moore",
    "  - Jameka Blanchard",
    "  - Ryan Sides (SWX)",
    "  - Quinn James",
    "  - Brayden Hallows",
    "",
    "PROJECTS returned: 89",
    "\nField shape of one project object:",
    "  id: number = 11289398",
    "  archived: boolean = false",
    "  archived_at: null",
    "  description: null",
    "  guid: string = \"3fbd217e-7f18-4516-8666-6469b181776d\"",
    "  name: string = \"Tasks\"",
    "  parent_id: null",
    "  project_code: null",
    "  secureurl: null",
    "  secureurl_expiration: null",
    "  settings: number = 0",
    "  timeentry_lockout: number = -1",
    "  ends_at: string = \"2026-01-13\"",
    "  starts_at: string = \"2026-01-08\"",
    "  deleted_at: null",
    "  created_at: string = \"2026-01-08T15:35:30Z\"",
    "  updated_at: string = \"2026-01-08T15:35:30Z\"",
    "  use_parent_bill_rates: boolean = false",
    "  type: string = \"Project\"",
    "  project_state_id: number = 22409781",
    "  thumbnail: null",
    "  owner_id: number = 4215619",
    "  owner_name: string = \"Jameka Blanchard\"",
    "  phase_name: null",
    "  has_pending_updates: boolean = false",
    "  client: null",
    "  project_state: string = \"Confirmed\"",
    "  tags: object",
    "",
    "Sampling assignments + task durations for up to 8 projects:\n",
    "• PROJECT \"Tasks\" (id 11289398)",
    "    assignments: 0",
    "",
    "• PROJECT \"Atrium\" (id 11341231)",
    "    assignments: 5",
    "      id: number = 95478845",
    "      allocation_mode: string = \"percent\"",
    "      user_id: number = 4240368",
    "      assignable_id: number = 11341235",
    "      ends_at: string = \"2025-12-31\"",
    "      starts_at: string = \"2025-12-31\"",
    "      repetition_id: null",
    "      created_at: string = \"2026-01-23T18:31:18Z\"",
    "      updated_at: string = \"2026-01-23T20:29:29Z\"",
    "      all_day_assignment: boolean = true",
    "      resource_request_id: null",
    "      percent: number = 1",
    "      bill_rate: number = 1",
    "      bill_rate_id: number = 106732193",
    "      status: null",
    "      description: string = \"PRD Review\"",
    "      status_option_id: null",
    "      note: null",
    "    phases: 5",
    "      id: number = 11341235",
    "      archived: boolean = false",
    "      archived_at: null",
    "      description: null",
    "      guid: string = \"7de6fcb6-c468-440f-9eb0-7c714b768992\"",
    "      name: string = \"Atrium\"",
    "      parent_id: number = 11341231",
    "      project_code: null",
    "      secureurl: null",
    "      secureurl_expiration: null",
    "      settings: number = 0",
    "      timeentry_lockout: number = -1",
    "      ends_at: string = \"2026-01-08\"",
    "      starts_at: string = \"2025-12-15\"",
    "      deleted_at: null",
    "      created_at: string = \"2026-01-23T18:31:18Z\"",
    "      updated_at: string = \"2026-01-23T20:29:29Z\"",
    "      use_parent_bill_rates: boolean = true",
    "      type: string = \"Project\"",
    "      project_state_id: number = 22409781",
    "      thumbnail: null",
    "      owner_id: number = 4240368",
    "      owner_name: string = \"Madison Trumble\"",
    "      phase_name: string = \"Intake & Planning\"",
    "      has_pending_updates: boolean = false",
    "      client: null",
    "      project_state: string = \"Confirmed\"",
    "      tags: object",
    "",
    "• PROJECT \"Casper Cyber Program\" (id 11348393)",
    "    assignments: 5",
    "      id: number = 95602749",
    "      allocation_mode: string = \"percent\"",
    "      user_id: number = 4238359",
    "      assignable_id: number = 11348395",
    "      ends_at: string = \"2025-09-29\"",
    "      starts_at: string = \"2025-09-29\"",
    "      repetition_id: null",
    "      created_at: string = \"2026-01-26T22:48:38Z\"",
    "      updated_at: string = \"2026-01-26T23:21:07Z\"",
    "      all_day_assignment: boolean = true",
    "      resource_request_id: null",
    "      percent: number = 1",
    "      bill_rate: number = 1",
    "      bill_rate_id: number = 106780192",
    "      status: null",
    "      description: string = \"Develop Project Plan and Timeline\"",
    "      status_option_id: null",
    "      note: null",
    "    phases: 5",
    "      id: number = 11348395",
    "      archived: boolean = false",
    "      archived_at: null",
    "      description: null",
    "      guid: string = \"4e5bfa66-fcb0-4f18-a9a3-6a765bc9134d\"",
    "      name: string = \"Casper Cyber Program\"",
    "      parent_id: number = 11348393",
    "      project_code: null",
    "      secureurl: null",
    "      secureurl_expiration: null",
    "      settings: number = 0",
    "      timeentry_lockout: number = -1",
    "      ends_at: string = \"2025-10-24\"",
    "      starts_at: string = \"2025-09-29\"",
    "      deleted_at: null",
    "      created_at: string = \"2026-01-26T22:38:21Z\"",
    "      updated_at: string = \"2026-01-26T23:21:08Z\"",
    "      use_parent_bill_rates: boolean = true",
    "      type: string = \"Project\"",
    "      project_state_id: number = 22409781",
    "      thumbnail: null",
    "      owner_id: number = 4238359",
    "      owner_name: string = \"Ayrielle Jackson\"",
    "      phase_name: string = \"Intake & Planning\"",
    "      has_pending_updates: boolean = false",
    "      client: null",
    "      project_state: string = \"Confirmed\"",
    "      tags: object",
    "",
    "• PROJECT \"Tasks\" (id 11308738)",
    "    assignments: 2",
    "      id: number = 94809691",
    "      allocation_mode: string = \"percent\"",
    "      user_id: number = 4228250",
    "      assignable_id: number = 11308740",
    "      ends_at: string = \"2025-12-18\"",
    "      starts_at: string = \"2025-12-18\"",
    "      repetition_id: null",
    "      created_at: string = \"2026-01-13T21:37:20Z\"",
    "      updated_at: string = \"2026-01-13T21:37:20Z\"",
    "      all_day_assignment: boolean = true",
    "      resource_request_id: null",
    "      percent: number = 1",
    "      bill_rate: number = 1",
    "      bill_rate_id: number = 106394601",
    "      status: null",
    "      description: string = \"Discovery Meeting 1\"",
    "      status_option_id: null",
    "      note: null",
    "    phases: 1",
    "      id: number = 11308740",
    "      archived: boolean = false",
    "      archived_at: null",
    "      description: null",
    "      guid: string = \"3471c445-fb1b-43c2-9f20-14946baa63e7\"",
    "      name: string = \"Tasks\"",
    "      parent_id: number = 11308738",
    "      project_code: null",
    "      secureurl: null",
    "      secureurl_expiration: null",
    "      settings: number = 0",
    "      timeentry_lockout: number = -1",
    "      ends_at: string = \"2026-01-13\"",
    "      starts_at: string = \"2025-12-18\"",
    "      deleted_at: null",
    "      created_at: string = \"2026-01-13T21:37:19Z\"",
    "      updated_at: string = \"2026-01-27T14:17:27Z\"",
    "      use_parent_bill_rates: boolean = true",
    "      type: string = \"Project\"",
    "      project_state_id: number = 22409781",
    "      thumbnail: null",
    "      owner_id: number = 4215619",
    "      owner_name: string = \"Jameka Blanchard\"",
    "      phase_name: string = \"Complete\"",
    "      has_pending_updates: boolean = false",
    "      client: null",
    "      project_state: string = \"Confirmed\"",
    "      tags: object",
    "",
    "• PROJECT \"Auto Renewals - PL\" (id 11355688)",
    "    assignments: 1",
    "      id: number = 107058137",
    "      allocation_mode: string = \"percent\"",
    "      user_id: number = 4238406",
    "      assignable_id: number = 11785317",
    "      ends_at: string = \"2026-07-02\"",
    "      starts_at: string = \"2026-06-15\"",
    "      repetition_id: null",
    "      created_at: string = \"2026-07-10T20:52:30Z\"",
    "      updated_at: string = \"2026-07-10T20:52:30Z\"",
    "      all_day_assignment: boolean = true",
    "      resource_request_id: null",
    "      percent: number = 1",
    "      bill_rate: number = 1",
    "      bill_rate_id: number = 110161665",
    "      status: null",
    "      description: string = \"R2 Ops Testing\"",
    "      status_option_id: null",
    "      note: null",
    "    phases: 1",
    "      id: number = 11785317",
    "      archived: boolean = false",
    "      archived_at: null",
    "      description: null",
    "      guid: string = \"544205ab-77fc-41f6-9dce-74e6121b15cc\"",
    "      name: string = \"Auto Renewals - PL\"",
    "      parent_id: number = 11355688",
    "      project_code: null",
    "      secureurl: null",
    "      secureurl_expiration: null",
    "      settings: number = 0",
    "      timeentry_lockout: number = -1",
    "      ends_at: string = \"2026-07-02\"",
    "      starts_at: string = \"2026-06-15\"",
    "      deleted_at: null",
    "      created_at: string = \"2026-05-20T15:23:22Z\"",
    "      updated_at: string = \"2026-07-20T13:59:06Z\"",
    "      use_parent_bill_rates: boolean = true",
    "      type: string = \"Project\"",
    "      project_state_id: number = 22409781",
    "      thumbnail: null",
    "      owner_id: number = 4215619",
    "      owner_name: string = \"Jameka Blanchard\"",
    "      phase_name: string = \"Acceptance Testing (UAT/Pre-Prod)\"",
    "      has_pending_updates: boolean = false",
    "      client: null",
    "      project_state: string = \"Confirmed\"",
    "      tags: object",
    "",
    "• PROJECT \"Scottsdale API\" (id 11355703)",
    "    assignments: 5",
    "      id: number = 96132857",
    "      allocation_mode: string = \"percent\"",
    "      user_id: number = 4251699",
    "      assignable_id: number = 11355709",
    "      ends_at: string = \"2025-11-13\"",
    "      starts_at: string = \"2025-10-20\"",
    "      repetition_id: null",
    "      created_at: string = \"2026-02-03T20:16:50Z\"",
    "      updated_at: string = \"2026-02-18T20:26:09Z\"",
    "      all_day_assignment: boolean = true",
    "      resource_request_id: null",
    "      percent: number = 1",
    "      bill_rate: number = 1",
    "      bill_rate_id: number = 106980017",
    "      status: null",
    "      description: string = \"Define Project Scope and Objectives\"",
    "      status_option_id: null",
    "      note: null",
    "    phases: 5",
    "      id: number = 11355709",
    "      archived: boolean = false",
    "      archived_at: null",
    "      description: null",
    "      guid: string = \"cbc9dc10-82dd-46ce-89b4-811ee6c1153b\"",
    "      name: string = \"Scottsdale API\"",
    "      parent_id: number = 11355703",
    "      project_code: null",
    "      secureurl: null",
    "      secureurl_expiration: null",
    "      settings: number = 0",
    "      timeentry_lockout: number = -1",
    "      ends_at: string = \"2025-11-13\"",
    "      starts_at: string = \"2025-10-20\"",
    "      deleted_at: null",
    "      created_at: string = \"2026-01-28T18:31:29Z\"",
    "      updated_at: string = \"2026-06-11T14:25:25Z\"",
    "      use_parent_bill_rates: boolean = true",
    "      type: string = \"Project\"",
    "      project_state_id: number = 22409781",
    "      thumbnail: null",
    "      owner_id: null",
    "      owner_name: null",
    "      phase_name: string = \"Intake & Planning\"",
    "      has_pending_updates: boolean = false",
    "      client: null",
    "      project_state: string = \"Confirmed\"",
    "      tags: object",
    "",
    "• PROJECT \"Agency Fees\" (id 11356206)",
    "    assignments: 5",
    "      id: number = 96250425",
    "      allocation_mode: string = \"percent\"",
    "      user_id: number = 4215619",
    "      assignable_id: number = 11356210",
    "      ends_at: string = \"2025-10-14\"",
    "      starts_at: string = \"2025-10-14\"",
    "      repetition_id: null",
    "      created_at: string = \"2026-02-04T16:08:15Z\"",
    "      updated_at: string = \"2026-02-26T18:23:53Z\"",
    "      all_day_assignment: boolean = true",
    "      resource_request_id: null",
    "      percent: number = 1",
    "      bill_rate: number = 1",
    "      bill_rate_id: number = 107017628",
    "      status: null",
    "      description: string = \"Intake\"",
    "      status_option_id: null",
    "      note: null",
    "    phases: 3",
    "      id: number = 11356210",
    "      archived: boolean = false",
    "      archived_at: null",
    "      description: null",
    "      guid: string = \"9e7ea42e-dd0c-4d10-9be3-e378cf766d7a\"",
    "      name: string = \"Agency Fees\"",
    "      parent_id: number = 11356206",
    "      project_code: null",
    "      secureurl: null",
    "      secureurl_expiration: null",
    "      settings: number = 0",
    "      timeentry_lockout: number = -1",
    "      ends_at: string = \"2025-10-14\"",
    "      starts_at: string = \"2025-10-14\"",
    "      deleted_at: null",
    "      created_at: string = \"2026-01-28T20:06:55Z\"",
    "      updated_at: string = \"2026-02-26T18:23:53Z\"",
    "      use_parent_bill_rates: boolean = true",
    "      type: string = \"Project\"",
    "      project_state_id: number = 22409781",
    "      thumbnail: null",
    "      owner_id: number = 4215619",
    "      owner_name: string = \"Jameka Blanchard\"",
    "      phase_name: string = \"Intake & Planning\"",
    "      has_pending_updates: boolean = false",
    "      client: null",
    "      project_state: string = \"Confirmed\"",
    "      tags: object",
    "",
    "• PROJECT \"Agency Fees Management\" (id 11356209)",
    "    assignments: 5",
    "      id: number = 96265899",
    "      allocation_mode: string = \"percent\"",
    "      user_id: number = 4228250",
    "      assignable_id: number = 11401568",
    "      ends_at: string = \"2025-11-11\"",
    "      starts_at: string = \"2025-11-11\"",
    "      repetition_id: null",
    "      created_at: string = \"2026-02-04T18:42:49Z\"",
    "      updated_at: string = \"2026-02-18T20:29:37Z\"",
    "      all_day_assignment: boolean = true",
    "      resource_request_id: null",
    "      percent: number = 1",
    "      bill_rate: number = 1",
    "      bill_rate_id: number = 107027791",
    "      status: null",
    "      description: string = \"Collect Business Requirements from Stakeholders",
    "      status_option_id: null",
    "      note: null",
    "    phases: 5",
    "      id: number = 11401568",
    "      archived: boolean = false",
    "      archived_at: null",
    "      description: null",
    "      guid: string = \"77c1529c-0b6c-43bc-9cb4-07dcd6057316\"",
    "      name: string = \"Agency Fees Management\"",
    "      parent_id: number = 11356209",
    "      project_code: null",
    "      secureurl: null",
    "      secureurl_expiration: null",
    "      settings: number = 0",
    "      timeentry_lockout: number = -1",
    "      ends_at: string = \"2025-11-11\"",
    "      starts_at: string = \"2025-11-11\"",
    "      deleted_at: null",
    "      created_at: string = \"2026-02-04T18:42:48Z\"",
    "      updated_at: string = \"2026-02-18T20:29:37Z\"",
    "      use_parent_bill_rates: boolean = true",
    "      type: string = \"Project\"",
    "      project_state_id: number = 22409781",
    "      thumbnail: null",
    "      owner_id: number = 4215619",
    "      owner_name: string = \"Jameka Blanchard\"",
    "      phase_name: string = \"Collect Business Requirements from Stakeholders",
    "      has_pending_updates: boolean = false",
    "      client: null",
    "      project_state: string = \"Confirmed\"",
    "      tags: object",
    "",
    "=== NAME-MATCH GAP vs Portfolio Summary ===",
    "RM projects: 89",
    "  exact name match to a sheet project:      75",
    "  matched only after normalizing:           1",
    "  UNMATCHED (would need a fallback entry):   13",
    "\n  Unmatched RM names — these become the fallback map:",
    "    \"Tasks\"",
    "    \"Tasks\"",
    "    \"HVH GLISE Contract\"",
    "    \"API Service\"",
    "    \"GLISE State Expansion&nbsp; - Group 3 (MI, MN, ND, SD, WI, MT)\"",
    "    \"GLISE State Expansion&nbsp; - Group 2 (AZ, KY, NM, NV, OR, WA)\"",
    "    \"RM Time Off Requests\"",
    "    \"Project Plan - Markel Capacity Program\"",
    "    \"Jira\"",
    "    \"Maintenance Sprint Tracker\"",
    "    \"Project plan\"",
    "    \"Project Plan - Munich RE - Commercial\"",
    "    \"Project Plan - CertifID\""
  ]
};
